name: "Java BankCalc — Build & Test & Artifact"

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      run_example:
        description: "샘플 스크립트 실행해 보고 산출물 업로드"
        type: boolean
        default: true

permissions:
  contents: read

env:
  TZ: Asia/Seoul
  MAVEN_OPTS: -Xmx1g

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "maven"

      - name: Validate & Test
        run: mvn -q -e -DskipTests=false test

      - name: Package (fat jar manifest)
        run: mvn -q -e -DskipTests package

      - name: List target
        run: ls -al target

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bankcalc-jar
          path: target/bankcalc.jar
          if-no-files-found: error
          retention-days: 14

      - name: Run example (optional)
        if: ${{ inputs.run_example == true }}
        run: |
          mkdir -p outputs
          java -jar target/bankcalc.jar --start 100000 \
               --script scripts/sample-ops.csv \
               --interest 3.2 --days 30 \
               --export outputs/history.csv
          echo "FINAL_BALANCE=$(tail -n 1 outputs/history.csv | awk -F',' '{print $5}')" | tee -a $GITHUB_STEP_SUMMARY
          ls -al outputs

      - name: Upload outputs
        if: ${{ inputs.run_example == true }}
        uses: actions/upload-artifact@v4
        with:
          name: bankcalc-outputs
          path: outputs/**
          retention-days: 14
