name: Clone with GitHub CLI (no explicit login)

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: "클론할 저장소 (owner/repo 형식)"
        required: true
        default: "stack1302/test-repo"
      dest_dir:
        description: "클론 받을 폴더명"
        required: true
        default: "cloned-repo"

permissions:
  contents: read

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # ✅ 해결방법 1: gh auth login 없이 바로 사용
      - name: Clone target repository with GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          REPO="${{ github.event.inputs.target_repo }}"
          DEST="${{ github.event.inputs.dest_dir }}"
          echo "Cloning ${REPO} -> ${DEST}"
          gh repo clone "$REPO" "$DEST"
          echo "Done."

      - name: List cloned files
        run: |
          ls -alh "${{ github.event.inputs.dest_dir }}" || true
