name: Clone Repo Example

on:
  workflow_dispatch:  # 수동 실행용
  push:               # 혹은 push 시 실행

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Clone target repository
        run: |
          # 여기서 정확한 저장소 경로 작성 (예시: stack1302/test-repo)
          gh repo clone stack1302/test-repo cloned-repo

      - name: List cloned files
        run: |
          ls -R cloned-repo
